# Generated by Django 5.1.1 on 2024-09-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRCodes', '0002_remove_driver_license_driver_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='licence_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
